/**
 * ChromaDB Vector Database Service
 * Advanced AI Agent Architecture - Vector Database Integration
 * 
 * This service provides the core vector database functionality using ChromaDB
 * with support for multiple collections and embedding operations.
 */

const { ChromaClient } = require('chromadb');
const crypto = require('crypto');

class ChromaDBService {
    constructor(config = {}) {
        this.config = {
            host: config.host || 'localhost',
            port: config.port || 8000,
            collections: config.collections || [
                'user_knowledge',
                'code_patterns', 
                'project_context'
            ],
            defaultCollection: config.defaultCollection || 'user_knowledge'
        };
        
        this.client = null;
        this.collections = new Map();
        this.isConnected = false;
    }

    /**
     * Initialize the ChromaDB client and collections
     */
    async initialize() {
        try {
            console.log('Initializing ChromaDB service...');
            
            // Create ChromaDB client
            this.client = new ChromaClient({
                baseUrl: `http://${this.config.host}:${this.config.port}`
            });

            // Test connection
            await this.client.heartbeat();
            this.isConnected = true;
            
            // Initialize collections
            await this.initializeCollections();
            
            console.log('ChromaDB service initialized successfully');
            return true;
        } catch (error) {
            console.error('Failed to initialize ChromaDB service:', error);
            throw new Error(`ChromaDB initialization failed: ${error.message}`);
        }
    }

    /**
     * Initialize all configured collections
     */
    async initializeCollections() {
        try {
            for (const collectionName of this.config.collections) {
                await this.createCollection(collectionName);
            }
        } catch (error) {
            console.error('Failed to initialize collections:', error);
            throw error;
        }
    }

    /**
     * Create or get existing collection
     */
    async createCollection(name, metadata = {}) {
        try {
            if (this.collections.has(name)) {
                return this.collections.get(name);
            }

            // Check if collection exists
            const collections = await this.client.listCollections();
            const existingCollection = collections.find(col => col.name === name);

            let collection;
            if (existingCollection) {
                collection = await this.client.getCollection({ name });
            } else {
                collection = await this.client.createCollection({
                    name,
                    metadata: {
                        ...metadata,
                        created_at: new Date().toISOString(),
                        embedding_model: 'sentence-transformers/all-MiniLM-L6-v2'
                    }
                });
            }

            this.collections.set(name, collection);
            console.log(`Collection '${name}' ready`);
            return collection;
        } catch (error) {
            console.error(`Failed to create/get collection '${name}':`, error);
            throw error;
        }
    }

    /**
     * Insert document with embedding
     */
    async insertDocument(collectionName, text, metadata = {}, id = null) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            // Generate ID if not provided
            const documentId = id || this.generateDocumentId(text, metadata);
            
            // Add document to collection
            await collection.add({
                ids: [documentId],
                embeddings: null, // Will be generated by ChromaDB
                metadatas: [metadata],
                documents: [text]
            });

            console.log(`Document inserted into '${collectionName}': ${documentId}`);
            return documentId;
        } catch (error) {
            console.error('Failed to insert document:', error);
            throw error;
        }
    }

    /**
     * Retrieve context using semantic search
     */
    async retrieveContext(collectionName, query, k = 5, filters = {}) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            // Perform similarity search
            const results = await collection.query({
                queryTexts: [query],
                nResults: k,
                where: filters
            });

            // Format results
            const formattedResults = results.ids[0].map((id, index) => ({
                id,
                document: results.documents[0][index],
                metadata: results.metadatas[0][index],
                distance: results.distances[0][index],
                similarity: 1 - results.distances[0][index] // Convert distance to similarity
            }));

            console.log(`Retrieved ${formattedResults.length} documents from '${collectionName}'`);
            return formattedResults;
        } catch (error) {
            console.error('Failed to retrieve context:', error);
            throw error;
        }
    }

    /**
     * Update existing document
     */
    async updateDocument(collectionName, id, newText, newMetadata = {}) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            // Update document
            await collection.update({
                ids: [id],
                metadatas: [newMetadata],
                documents: [newText]
            });

            console.log(`Document updated in '${collectionName}': ${id}`);
            return true;
        } catch (error) {
            console.error('Failed to update document:', error);
            throw error;
        }
    }

    /**
     * Delete document by ID
     */
    async deleteDocument(collectionName, id) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            await collection.delete({ ids: [id] });
            console.log(`Document deleted from '${collectionName}': ${id}`);
            return true;
        } catch (error) {
            console.error('Failed to delete document:', error);
            throw error;
        }
    }

    /**
     * Perform semantic search across multiple collections
     */
    async semanticSearch(query, k = 5, collectionNames = null) {
        try {
            const collectionsToSearch = collectionNames || this.config.collections;
            const allResults = [];

            for (const collectionName of collectionsToSearch) {
                if (this.collections.has(collectionName)) {
                    const results = await this.retrieveContext(collectionName, query, k);
                    results.forEach(result => {
                        allResults.push({
                            ...result,
                            collection: collectionName
                        });
                    });
                }
            }

            // Sort by similarity and return top k results
            allResults.sort((a, b) => b.similarity - a.similarity);
            return allResults.slice(0, k);
        } catch (error) {
            console.error('Failed to perform semantic search:', error);
            throw error;
        }
    }

    /**
     * Get collection statistics
     */
    async getCollectionStats(collectionName) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            const count = await collection.count();
            return {
                name: collectionName,
                documentCount: count,
                embeddingDimension: 384, // MiniLM-L6-v2 dimension
                status: 'active'
            };
        } catch (error) {
            console.error('Failed to get collection stats:', error);
            throw error;
        }
    }

    /**
     * Cleanup old documents
     */
    async cleanupOldDocuments(collectionName, daysToKeep = 30) {
        try {
            const collection = this.collections.get(collectionName);
            if (!collection) {
                throw new Error(`Collection '${collectionName}' not found`);
            }

            const cutoffDate = new Date();
            cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);

            // Get all documents with timestamps
            const results = await collection.get({
                where: {
                    created_at: { $lt: cutoffDate.toISOString() }
                }
            });

            if (results.ids.length > 0) {
                await collection.delete({ ids: results.ids });
                console.log(`Cleaned up ${results.ids.length} old documents from '${collectionName}'`);
            }

            return results.ids.length;
        } catch (error) {
            console.error('Failed to cleanup old documents:', error);
            throw error;
        }
    }

    /**
     * Generate unique document ID
     */
    generateDocumentId(text, metadata) {
        const content = `${text}${JSON.stringify(metadata)}`;
        return crypto.createHash('sha256').update(content).digest('hex').substring(0, 16);
    }

    /**
     * Check service health
     */
    async healthCheck() {
        try {
            if (!this.isConnected || !this.client) {
                return { status: 'disconnected', error: 'Not connected to ChromaDB' };
            }

            await this.client.heartbeat();
            
            const collectionStats = {};
            for (const [name, collection] of this.collections) {
                collectionStats[name] = await this.getCollectionStats(name);
            }

            return {
                status: 'healthy',
                collections: collectionStats,
                totalDocuments: Object.values(collectionStats).reduce((sum, stat) => sum + stat.documentCount, 0)
            };
        } catch (error) {
            return { status: 'unhealthy', error: error.message };
        }
    }

    /**
     * Close connections
     */
    async close() {
        try {
            this.collections.clear();
            this.isConnected = false;
            console.log('ChromaDB service closed');
        } catch (error) {
            console.error('Error closing ChromaDB service:', error);
        }
    }
}

module.exports = ChromaDBService;