tunnel: 6ec068de-d21e-4e82-a446-e02ed28f8569
credentials-file: /home/sahon/.cloudflared/6ec068de-d21e-4e82-a446-e02ed28f8569.json

ingress:
  - hostname: zombiecoder.my.id
    service: http://localhost:3001
  - hostname: app.zombiecoder.my.id
    service: http://localhost:8000
  - hostname: zombie.zombiecoder.my.id
    service: http://localhost:8000
  - service: http_status:404